FROM python:3.11.9-slim-bookworm
WORKDIR /app
RUN apt update && apt install -y curl build-essential
RUN pip install -U pip poetry==1.8.3
COPY pyproject.toml poetry.lock /app/
RUN poetry config virtualenvs.create false \
    && poetry install --no-cache --no-interaction --no-ansi
COPY src /app/
EXPOSE 80
CMD ["uvicorn", "main:app", "--host=0.0.0.0", "--port=80", "--reload"]