"""

Revision ID: aca41002e913
Revises: a0d3f2d5a4e1
Create Date: 2025-05-17 20:47:18.210008

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aca41002e913"
down_revision: Union[str, None] = "a0d3f2d5a4e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "requests", sa.Column("input_token_count", sa.Integer(), nullable=True)
    )
    op.add_column(
        "requests", sa.Column("output_token_count", sa.Integer(), nullable=True)
    )
    op.add_column(
        "requests", sa.Column("total_token_count", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("requests", "total_token_count")
    op.drop_column("requests", "output_token_count")
    op.drop_column("requests", "input_token_count")
    # ### end Alembic commands ###
